#%RAML 1.0 DataType
properties:
  token:
    description: slack integration app token
    required: true
    type: string
  response_url:
    description: Request URL to be used to send response message
    required: true
    type: string
  text:
    description: input text from slack
    required: true
    type: string